### ISSUE TITLE
Allow launching another app

### ISSUE THREAD

**Issue by yurik94** [derohimat/KioskMode-Android#2]
Hello,

Thank you for this sample, worked after upgrading some dependencies and factory reset.
I have a question: how can I whitelist some activities/apps ?

**Comment by derohimat** [comment]
Hello @yurik94,

Currently I just make this sample for just one app. For make whitlist, I'm still not research for that.

**Comment by yurik94** [comment]
nevermind, I found the way 👍 

```
mDpm.setLockTaskPackages(
                        deviceAdmin, //deviceAdmin = new ComponentName(this, AdminReceiver.class);
                        whitelistedPackages); //String[]
```

**Comment by amet123** [comment]
I want only enaable for emergency call rest disable,

**Comment by shahdghorsi** [comment]
Hello, thank you so much for this useful app I just wonder where to add the whitelist

**Comment by derohimat** [comment]
@shahdghorsi you can see at readme or comment from here https://github.com/derohimat/KioskMode-Android/issues/2#issuecomment-434504722

**Comment by derohimat** [comment]
> I want only enaable for emergency call rest disable,

@amet123 Sorry, currently I'm not research for that

**Comment by shahdghorsi** [comment]
Thank you so much

**Comment by alexfuser** [comment]
@yurik94 Could you please tell me, where do I place those lines for the whitelist?
